import { useAppDispatch, useAppSelector } from "@/hooks/useAppDispatch";
import { searchProducts } from "@/store/search/actions";
import { ISearchState } from "@/store/search/types";
import { generateKey } from "@/utils/generateKey";
import Head from "next/head";
import { useCallback, useEffect } from "react";
import Header from "./components/Header";
import Product from "./components/Product";
import styles from "./home.module.css";
export default function Home() {
  const dispatch = useAppDispatch();
  const { products } = useAppSelector((state) => state.search);
  // eslint-disable-next-line react-hooks/exhaustive-deps
  const params = { searchTerm: "Apple iPod 5", sort: "", price: "" };

  const getProducts = useCallback(() => {
    dispatch(searchProducts(params));
  }, [dispatch, params]);

  useEffect(() => {
    getProducts();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [dispatch]);
  return (
    <>
      <Head>
        <title>Mercado Livre - Teste Frontend</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="icon"
          href={
            "https://http2.mlstatic.com/frontend-assets/ml-web-navigation/ui-navigation/5.21.22/mercadolibre/favicon.svg"
          }
        />
      </Head>
      <main className={styles.main}>
        <Header />
        {products.length && (
          <div className={styles.WrapperProducts}>
            {products.map((product: ISearchState) => (
              <Product key={generateKey()} item={product} />
            ))}
          </div>
        )}
      </main>
    </>
  );
}
